### ISSUE TITLE
Can't Generate Pokemon Pages [0.12.0]

### ISSUE THREAD

**Issue by Aberlolz** [AkeemAllen/WikiGen#70]
Hey there!
Running Opensuse Tumbleweed.

I can't generate Pokemon, once I select a range the loading symbol on the Generate Pages button just keeps spinning, tried it multiple times, and kept it running for quite a while with nothing happening. Clicking in any search field, I get a "Creating a new option..." pop up below it. using Version 0.12.0 tried the rpm package, as well as the AppImage.

Version 0.11.0 doesn't have these Issues.

Does the program generate some logs i could throw your way?

**Comment by AkeemAllen** [comment]
Hey @Aberlolz 
Apologies for just now seeing your issue...3 weeks later. Not sure how I missed it.

Update the app to the latest version. It's 1.1.2 as of this post.
